create table app_user
(
 id bigint generated by default as identity,
 email varchar(255),
 login varchar(255),
 password varchar(255),
 role varchar(255),
 username varchar(255),
 group_id bigint,
 primary key (id));


create table invite_code
(id bigint generated by default as identity,
 code integer,
 expired_time time,
 user_id bigint,
 primary key (id)
);



create table user_group
(id bigint generated by default as identity,
 primary key (id),
 name varchar(128));



alter table app_user
    add constraint unique_email unique (email);


alter table app_user
    add constraint app_user_user_group_FK foreign key (group_id) references user_group;


alter table invite_code
    add constraint invite_code_app_user_FK foreign key (user_id) references app_user;

