create table meal (
    id bigint generated by default as identity ,
    recipe_id bigint,
    portions int,
    meal_type varchar(32) check (meal_type in ('BREAKFAST', 'LUNCH', 'DINNER')),
    date date,
    group_id bigint,
    primary key (id)
);

alter table meal
    add constraint meal_recipe_id_FK foreign key (recipe_id) references recipe;

alter table meal
    add constraint meal_group_id_FK foreign key (group_id) references user_group;

create table meal_ingredient (
    meal_id bigint,
    ingredient_id bigint,
    qty float,
    primary key (meal_id, ingredient_id)
);

alter table meal_ingredient
    add constraint meal_ingredient_meal_id_FK foreign key (meal_id) references meal;

alter table meal_ingredient
    add constraint meal_ingredient_product_id_FK foreign key (ingredient_id) references product;



