create table synchronization_product(
    id bigint generated by default as identity,
    product_id bigint,
    group_id bigint,
    qty float,
    primary key (id)
);

alter table synchronization_product
    add constraint synchronization_product_id_FK foreign key (product_id) references product;

alter table synchronization_product
    add constraint synchronization_group_id_FK foreign key (group_id) references user_group;