create table category(
                         id bigint generated by default as identity,
                         category varchar(255) not null unique ,
                         primary key (id)
);


create table product(
                        id bigint generated by default as identity,
                        name varchar(255) not null ,
                        category_id bigint not null ,
                        group_created_id bigint not null ,
                        unit varchar(255) not null check (unit in ('L', 'KG', 'GR', 'SZT', 'ML')),
                        primary key (id)
);

create table shop_product_group(
                                   id bigint generated by default as identity,
                                   amount float check (amount > 0),
                                   product_id bigint not null ,
                                   group_owner_id bigint not null ,
                                   state varchar(255) check ( state in ( 'BUY', 'BOUGHT', 'PANTRY' ))
);

alter table product
    add constraint group_productFK foreign key (group_created_id) references user_group;

alter table product
    add constraint category_productFK foreign key (category_id) references category;


alter table shop_product_group
    add constraint group_owner_shop_productFK foreign key (group_owner_id) references user_group;

alter table shop_product_group
    add constraint product_shopFK foreign key (product_id) references product;