name: Deploy on Goole Cloud App Engine

on:
  push:
    branches: ["INZ-334"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Adding secret
      shell: bash
      run: |
        echo $DEV_PROP_FILE >> src/main/resources/application.properties
        cat src/main/resources/application.properties