# https://github.com/marketplace/actions/read-file-content
name: Deploy on Goole Cloud App Engine

on:
  push:
    branches: ["INZ-334"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SECRET }}
      run: |
        echo "$SUPER_SECRET"

    - name: Read file
      id: file
      uses: jaywcjlove/github-action-read-file@main
      with:
        path: src/main/resources/application.properties
